### ISSUE TITLE
Gimp: change Theme to "system"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#57]
![screenshot_20180712_145812](https://user-images.githubusercontent.com/840070/42634777-728720be-85e4-11e8-8fa8-7f98be5e8a75.png)

**Comment by NuLogicSystems** [comment]
Netrunner rolling ships Gimp 5.10, the netrunner-common/default-settings-applications settings are for Gimp 2.8. These are not picked up by or caried over (merged) into Gimp 2.10. The toolsrc file has changed to use stock-id instead of icon-name now. So far that's the only major change I've found besides location of config files. The new location is ~/.config/GIMP/2.10

**Comment by llelectronics** [comment]
Yep only relevant for Gimp 2.10. 2.8 actually has no "System" Theme. Gimp 2.10 is in Debian Sid currently. Will perform the change after it landed in testing.

**Comment by NuLogicSystems** [comment]
Should I go ahead and merge our old changes into ~/.config/GIMP/2.10 with the syntax changes, and then add the gimprc file for the theme change for rolling and/or future proffing debian edition?

**Comment by llelectronics** [comment]
Yep please do so

**Comment by NuLogicSystems** [comment]
Will do as soon as I get back to the office.

**Comment by NuLogicSystems** [comment]
Done

**Comment by star-buck** [comment]
@llelectronics : is that in debian as well?

**Comment by llelectronics** [comment]
Yes. It is part of default-settings-applications and already packaged for Netrunner Debian.
